name: CRON Background Training

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'     # каждые 5 мин

jobs:
  background-training:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Attempt to download previous artifacts
      id: download-artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: cron.yml
        name: model
        path: ./model_artifacts
        workflow_conclusion: success
        branch: main
      continue-on-error: true

    - name: Attempt to download previous artifacts 2
      id: download-artifact-2
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: cron.yml
        name: preprocessor
        path: .
        workflow_conclusion: success
        branch: main
      continue-on-error: true
      
    - name: Attempt to download previous artifacts 3
      id: download-artifact-3
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: cron.yml
        name: dataloader
        path: .
        workflow_conclusion: success
        branch: main
      continue-on-error: true
    
    - name: Run initial training script
      if: steps.download-artifact-3.outcome == 'failure'
      run: |
        python mvp/pipeline_manager.py create_model

    - name: Run training script with periodic artifact generation
      if: steps.download-artifact-3.outcome == 'success'
      run: |
        python mvp/pipeline_manager.py update
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: training-logs
        path: logfile.log

    - name: Upload model
      uses: actions/upload-artifact@v4
      with:
        name: model
        path: ./model_artifacts/current_model.json

    - name: Upload dataloader
      uses: actions/upload-artifact@v4
      with:
        name: dataloader
        path: dataloader.pkl
        
    - name: Upload preprocessor
      uses: actions/upload-artifact@v4
      with:
        name: preprocessor
        path: preprocessor.pkl
        

