name: CRON Background Training

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'     # каждые 5 мин

jobs:
  background-training:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Attempt to download previous artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: cron.yml
        name: current_model.json
        path: ./models
        workflow_conclusion: success
        branch: main
      continue-on-error: true

    - name: Run training script with periodic artifact generation
      run: |
        python mvp/pipeline_manager.py update
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: training-logs
        path: logfile.log

    - name: Upload model
      uses: actions/upload-artifact@v4
      with:
        name: model
        path: current_model.json

    - name: Upload dataloader
      uses: actions/upload-artifact@v4
      with:
        name: dataloader
        path: dataloader.pkl

    - name: Upload TensorBoard logs
      uses: actions/upload-artifact@v4
      with:
        name: tensorboard-logs
        path: runs/
