name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Показать содержимое директории
      run: ls -R

    - name: Run training script
      run: |
        python mvp/pipeline_manager.py create_model

    - name: Показать содержимое директории
      run: ls -R
      
    - name: Run tests
      run: |
        python -m unittest discover tests

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: training-logs
        path: logfile.log

    - name: Upload model
      uses: actions/upload-artifact@v4
      with:
        name: model
        path: ./model_artifacts/current_model.json
        
    - name: Upload dataloader
      uses: actions/upload-artifact@v4
      with:
        name: dataloader
        path: dataloader.pkl
        
    - name: Upload preprocessor
      uses: actions/upload-artifact@v4
      with:
        name: preprocessor
        path: preprocessor.pkl

